Map<String, String> get km => {
      "Warning": "ព្រមាន",
      "Error": "បរាជ័យ",
      "Success": "ជោគជ័យ",
      "No Content": "គ្មានទិន្នន័យ",
      "Bad Request": "ការស្នើរសុំបរាជ័យ",
      "Unauthorized": "ពុំមានសិទ្ធិ",
      "Not Found": "ស្វែងរកមិនឃើញ",
      "Connection Timeout": "អស់ពេលនៃការតភ្ជាប់",
      "Add": "បញ្ចូល",
      "Edit": "កែប្រែ",
      "Delete": "លុប",
      "Cancel": "បោះបង់",
      "Ok": "យល់ព្រម",
      "Powered By": "រក្សាសិទ្ធិដោយ",
      "Version": "ជំនាន់ទី",
      "Processing": "កំពុងដំណើរការ",
      "Empty Data": "ទិន្ន័យទទេ",
      "Login": "ចូលប្រើប្រាស់",
      "Logout": "ចាកចេញ",
      "More": "ផ្សេងៗ",
      "Back": "ត្រឡប់ក្រោយ",
      "Save": "រក្សាទុក",
      "Reload": "ផ្ទុកឡើងវិញ",
      "Username": "អ្នកប្រើប្រាស់",
      "Password": "លេខសម្ងាត់",
      "PIN Code": "លេខ PIN",
      "Switch Language": "ប្ដូរភាសា",
      "Property Code": "កូដទីតាំងអាជីវកម្ម",
      "Property ID": "លេខសម្គាល់អាជីវកម្ម",
      "Never connect": "មិនធ្លាប់ភ្ជាប់",
      "Server URL": "តំណភ្ជាប់ម៉ាស៊ីនមេ",
      "Device": "ឧបករណ៍",
      "Invalid DateTime": "ប្រភេទថ្ងៃខែមិនត្រឹមត្រូវ",
      "Invalid Server URL": "តំណភ្ជាប់ម៉ាស៊ីនមេមិនត្រឹមត្រូវ",
      "Property ID cannot be blank": "កូដទីតាំងអាជីវកម្មមិនអាចចន្លោះទទេ",
      "Welcome Back": "សូមស្វាគមន៍ត្រឡប់មកវិញ",
      "Latest": "ចុងក្រោយ",
      "License was expired": "អាជ្ញាបណ្ណ័ត្រូវបានផុតកំណត់",
      "License was expired day ago": "អាជ្ញាបណ្ណ័ត្រូវបានផុតកំណត់ @day ថ្ងៃ",
      "Expiry on": "ផុតកំណត់នៅថ្ងៃទី @day @_days",
      "day(s)": "ថ្ងៃ",
      "Continue": "បន្ដ",
      "Property ID does not exist":
          "កូដទីតាំងអាជីវកម្ម(@code)មិនមានក្នុងប្រព័ន្ធទេ",
      "License Not Activated": "អាជ្ញាប័ណ្ណមិនទាន់ធ្វើឱ្យសកម្ម",
      "License Activated": "អាជ្ញាប័ណ្ណបានធ្វើឱ្យសកម្ម",
      "Invalid PIN Code": "លេខPIN មិនត្រឹមត្រូវ",
      "PIN Code can not be blank": "លេខPIN មិនអាចទទេ",
      "You're loss connection to server":
          "អ្នកបាត់បង់ការតភ្ជាប់ទៅកាន់ម៉ាស៊ីនមេ",
      "Setting": "កំណត់",
      "Hello": "សួស្ដី",
      "Good morning": "អរុណសួស្តី",
      "Good afternoon": "សួស្តី",
      "Good evening": "សាយណ្ហសួស្តី",
      "POS Profile": "ទីតាំងគិតប្រាក់",
      "Money In / Out": "ប្រាក់ចូល / ចេញ",
      "Receipt": "វិក្កយបត្រ",
      "POS": "ចូលលក់",
      "Customer": "អតិថិជន",
      "Pending Invoice": "វិក្កយបត្រកំពុងរង់ចាំ",
      "Reports": "របាយការណ៍",
      "Other": "ផ្សេងៗ",
      "Switch POS Profile": "ប្ដូរទីតាំងគិតប្រាក់",
      "Printing": "ការបោះពុម្ភ",
      "Help Center": "ជំនួយ",
      "Exchange Rate": "អត្រាប្ដូរប្រាក់",
      "My Account": "គណនីរបស់ខ្ញុំ",
      "WiFi Password": "លេខសម្ងាត់ WiFi",
      "Promotions": "ការបញ្ចុះតម្លៃពិសេស",
      "Theme Mode": "របៀបរចនាប័ទ្ម",
      "Get Started": "ចាប់ផ្ដើម",
      "Next": "បន្ទាប់",
      "Sell": "លក់",
      "Boost sales performance using our intuitive Point of Sale (POS) system. Streamline checkout and receipt management.":
          "បង្កើនប្រសិទ្ធភាពការលក់ដោយប្រើប្រព័ន្ធចំណុចលក់ (POS) ដែលងាយស្រួលប្រើ។ ធ្វើឲ្យដំណើរការទូទាត់ និងគ្រប់គ្រងវិក្កយបត្រកាន់តែងាយស្រួល។",
      "Manage": "គ្រប់គ្រង",
      "Manage multiple businesses with ease. Keep track of all your customers, sales, expenses and product management in one place.":
          "គ្រប់គ្រងអាជីវកម្មជាច្រើនបានយ៉ាងងាយស្រួល។ តាមដានអតិថិជន ការលក់ ចំណាយ និងការគ្រប់គ្រងផលិតផលទាំងអស់នៅកន្លែងតែមួយ។",
      "Analyze": "វិភាគ",
      "Gain data-driven insights. Unlock the potential of analytics for informed decision-making to boost your income and lower expenses.":
          "ទទួលបានការយល់ដឹងផ្អែកលើទិន្នន័យ។ ប្រើប្រាស់ការវិភាគដើម្បីជួយសម្រេចចិត្តបានល្អប្រសើរ បង្កើនប្រាក់ចំណូល និងកាត់បន្ថយចំណាយ។",
      "Welcome back": "សូមស្វាគមន៍មកវិញ",
      "controll your business": "គ្រប់គ្រងអាជីវកម្មរបស់អ្នក",
      "Continue with Phone": "បន្តដោយប្រើលេខទូរស័ព្ទ",
      "Continue with Email": "បន្តដោយប្រើអ៊ីមែល",
      "I have an account": "ខ្ញុំមានគណនីរួចហើយ",
      "Sign Up": "ចុះឈ្មោះ",
      "Powered by": "រក្សាសិទ្ធិដោយ",
      "All rights reserved": "រក្សាសិទ្ធិគ្រប់យ៉ាង",
      "Create Account": "បង្កើតគណនី",
      "Select how you would like to create your business account.":
          "សូមជ្រើសរើសរបៀបដែលអ្នកចង់បង្កើតគណនីអាជីវកម្មរបស់អ្នក។",
      "Select how you would like to sign in to your business account.":
          "សូមជ្រើសរើសវិធីដែលអ្នកចង់ប្រើដើម្បីចូលគណនីអាជីវកម្មរបស់អ្នក។",
      "Choose Registration Method": "ជ្រើសរើសវិធីចុះឈ្មោះ",
      "Already have an account?": "មានគណនីរួចហើយមែនទេ?",
      "Don't have an account?": "មិនទាន់មានគណនីមែនទេ?",
      "Sign In to ePOS": "ចូលប្រើ ePOS",
      "Phone Number": "លេខទូរស័ព្ទ",
      "Phone": "លេខទូរស័ព្ទ",
      "Email Address": "អាសយដ្ឋានអ៊ីមែល",
      "Register using a secure SMS code":
          "ចុះឈ្មោះដោយប្រើកូដ SMS ដែលមានសុវត្ថិភាព",
      "Sign in using a secure SMS code":
          "ចូលគណនីដោយប្រើលេខកូដ SMS ដែលមានសុវត្ថិភាព",
      "Standard email and password setup": "ប្រើអ៊ីមែល និងពាក្យសម្ងាត់ធម្មតា",
      "Register Business": "ចុះឈ្មោះអាជីវកម្ម",
      "Business Type": "ប្រភេទអាជីវកម្ម",
      "Business Name": "ឈ្មោះអាជីវកម្ម",
      "First Name": "នាមខ្លួន",
      "Last Name": "នាមត្រកូល",
      "Quick Access PIN": "លេខសម្ងាត់ PIN ចូលប្រើរហ័ស",
      "Tell us about your business to get started.":
          "ប្រាប់យើងអំពីអាជីវកម្មរបស់អ្នក ដើម្បីចាប់ផ្តើមប្រើប្រាស់។",
      "I agree to the Terms of Service and Privacy Policy.":
          "ខ្ញុំយល់ព្រមនឹង លក្ខខណ្ឌនៃសេវាកម្ម និង គោលការណ៍ភាពឯកជន។",
      "This PIN will be used for fast terminal switching.":
          "លេខសម្ងាត់ PIN នេះ នឹងត្រូវបានប្រើសម្រាប់ប្ដូរទៅកាន់ម៉ាស៊ីនលក់ (Terminal) បានយ៉ាងរហ័ស។",
      "Complete Registration": "បញ្ចប់ការចុះឈ្មោះ",
      "Bank-grade security standards": "ស្តង់ដារសុវត្ថិភាពកម្រិតធនាគារ",
      "Save Draft for Later": "រក្សាទុកសម្រាប់ពេលក្រោយ",
      "Tell us about your business to get started. Join thousands of establishments managing operations with ePOS App.":
          "ប្រាប់យើងអំពីអាជីវកម្មរបស់អ្នក ដើម្បីចាប់ផ្តើម។ ចូលរួមជាមួយអាជីវកម្មរាប់ពាន់ដែលកំពុងគ្រប់គ្រងប្រតិបត្តិការជាមួយកម្មវិធី ePOS App។",
      "Invalid Phone Number": "លេខទូរស័ព្ទមិនត្រឹមត្រូវ",
      "PIN code allows numbers only": "លេខកូដ PIN ប្រើបានតែលេខប៉ុណ្ណោះ",
      "Search country": "ស្វែងរកប្រទេស",
      "Please agree to the terms to continue.": "សូមយល់ព្រមលក្ខខណ្ឌ ដើម្បីបន្ត",
      "Confirm": "បញ្ជាក់",
      "The business name is required.": "សូមបញ្ចូលឈ្មោះអាជីវកម្ម",
      "Please enter your first name.": "សូមបញ្ចូលនាមខ្លួន",
      "The business name must be more than 2 characters.":
          "ឈ្មោះអាជីវកម្មត្រូវមានយ៉ាងហោចណាស់ ៣ តួអក្សរ",
      "Verification": "ការផ្ទៀងផ្ទាត់",
      "Verification Code": "លេខកូដផ្ទៀងផ្ទាត់",
      "Didn't receive the code?": "មិនទទួលបានលេខកូដមែនទេ?",
      "Resend Code": "ផ្ញើលេខកូដម្ដងទៀត",
      "Verify": "ផ្ទៀងផ្ទាត់",
      "Choose Sign In Method": "ជ្រើសរើសវិធីចូលគណនី",
      "Sign In": "ចូលគណនី"
    };
